# Generated by Django 4.1.7 on 2023-03-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Аватар'),
        ),
    ]
