# Generated by Django 4.1.7 on 2023-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chatuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
